### ISSUE TITLE
Parrot Explosion!

### ISSUE THREAD

**Issue by jmhobbs** [lambtron/emojipacks#32]
Party Parrot had been getting lots on new parrots recently.   I've set things up so when a new parrot is added it updates a YAML here:  http://cultofthepartyparrot.com/parrotparty.yaml

What's the best way to get that synced into this repo?

Thanks!

**Comment by hugovk** [comment]
@jmhobbs The easiest way is to periodically submit updated YAML files.

**Comment by aendra-rininsland** [comment]
@jmhobbs You are a gentleman and a scholar.

*edit:* That said, this isn't working — most of your names have spaces in them, which silently fails emojipacks. Updated version:

```
title: parrotparty
emojis:
  - name: parrot
    src: 'http://cultofthepartyparrot.com/parrots/parrot.gif'
  - name: middleparrot
    src: 'http://cultofthepartyparrot.com/parrots/middleparrot.gif'
  - name: rightparrot
    src: 'http://cultofthepartyparrot.com/parrots/rightparrot.gif'
  - name: aussieparrot
    src: 'http://cultofthepartyparrot.com/parrots/aussieparrot.gif'
  - name: gothparrot
    src: 'http://cultofthepartyparrot.com/parrots/gothparrot.gif'
  - name: oldtimeyparrot
    src: 'http://cultofthepartyparrot.com/parrots/oldtimeyparrot.gif'
  - name: boredparrot
    src: 'http://cultofthepartyparrot.com/parrots/boredparrot.gif'
  - name: shuffleparrot
    src: 'http://cultofthepartyparrot.com/parrots/shuffleparrot.gif'
  - name: shufflefurtherparrot
    src: 'http://cultofthepartyparrot.com/parrots/shufflefurtherparrot.gif'
  - name: congaparrot
    src: 'http://cultofthepartyparrot.com/parrots/congaparrot.gif'
  - name: reversecongaparrot
    src: 'http://cultofthepartyparrot.com/parrots/reversecongaparrot.gif'
  - name: partyparrot
    src: 'http://cultofthepartyparrot.com/parrots/partyparrot.gif'
  - name: sadparrot
    src: 'http://cultofthepartyparrot.com/parrots/sadparrot.gif'
  - name: parrotcop
    src: 'http://cultofthepartyparrot.com/parrots/parrotcop.gif'
  - name: fastparrot
    src: 'http://cultofthepartyparrot.com/parrots/fastparrot.gif'
  - name: slowparrot
    src: 'http://cultofthepartyparrot.com/parrots/slowparrot.gif'
  - name: parrotdad
    src: 'http://cultofthepartyparrot.com/parrots/parrotdad.gif'
  - name: dealwithitparrot
    src: 'http://cultofthepartyparrot.com/parrots/dealwithitparrot.gif'
  - name: fiestaparrot
    src: 'http://cultofthepartyparrot.com/parrots/fiestaparrot.gif'
  - name: pizzaparrot
    src: 'http://cultofthepartyparrot.com/parrots/pizzaparrot.gif'
  - name: hamburgerparrot
    src: 'http://cultofthepartyparrot.com/parrots/hamburgerparrot.gif'
  - name: bananaparrot
    src: 'http://cultofthepartyparrot.com/parrots/bananaparrot.gif'
  - name: chillparrot
    src: 'http://cultofthepartyparrot.com/parrots/chillparrot.gif'
  - name: explodyparrot
    src: 'http://cultofthepartyparrot.com/parrots/explodyparrot.gif'
  - name: shufflepartyparrot
    src: 'http://cultofthepartyparrot.com/parrots/shufflepartyparrot.gif'
  - name: parrot
    src: 'http://cultofthepartyparrot.com/parrots/ice-cream-parrot.gif'
  - name: sassyparrot
    src: 'http://cultofthepartyparrot.com/parrots/sassyparrot.gif'
  - name: confusedparrot
    src: 'http://cultofthepartyparrot.com/parrots/confusedparrot.gif'
  - name: aussiecongaparrot
    src: 'http://cultofthepartyparrot.com/parrots/aussiecongaparrot.gif'
  - name: aussiereversecongaparrot
    src: 'http://cultofthepartyparrot.com/parrots/aussiereversecongaparrot.gif'
  - name: parrotwave1
    src: 'http://cultofthepartyparrot.com/parrots/parrotwave1.gif'
  - name: parrotwave2
    src: 'http://cultofthepartyparrot.com/parrots/parrotwave2.gif'
  - name: parrotwave3
    src: 'http://cultofthepartyparrot.com/parrots/parrotwave3.gif'
  - name: parrotwave4
    src: 'http://cultofthepartyparrot.com/parrots/parrotwave4.gif'
  - name: parrotwave5
    src: 'http://cultofthepartyparrot.com/parrots/parrotwave5.gif'
  - name: parrotwave6
    src: 'http://cultofthepartyparrot.com/parrots/parrotwave6.gif'
  - name: parrotwave7
    src: 'http://cultofthepartyparrot.com/parrots/parrotwave7.gif'
  - name: congapartyparrot
    src: 'http://cultofthepartyparrot.com/parrots/congapartyparrot.gif'
  - name: moonwalkingparrot
    src: 'http://cultofthepartyparrot.com/parrots/moonwalkingparrot.gif'
  - name: coffeeparrot
    src: 'http://cultofthepartyparrot.com/parrots/coffeeparrot.gif'
  - name: parrotmustache
    src: 'http://cultofthepartyparrot.com/parrots/parrotmustache.gif'
  - name: christmasparrot
    src: 'http://cultofthepartyparrot.com/parrots/christmasparrot.gif'
  - name: witnessprotectionparrot
    src: 'http://cultofthepartyparrot.com/parrots/witnessprotectionparrot.gif'
  - name: parrotsleep
    src: 'http://cultofthepartyparrot.com/parrots/parrotsleep.gif'
  - name: parrotbeer
    src: 'http://cultofthepartyparrot.com/parrots/parrotbeer.gif'
  - name: darkbeerparrot
    src: 'http://cultofthepartyparrot.com/parrots/darkbeerparrot.gif'
  - name: blondesassyparrot
    src: 'http://cultofthepartyparrot.com/parrots/blondesassyparrot.gif'
  - name: bluescluesparrot
    src: 'http://cultofthepartyparrot.com/parrots/bluescluesparrot.gif'
  - name: gentlemanparrot
    src: 'http://cultofthepartyparrot.com/parrots/gentlemanparrot.gif'
  - name: margaritaparrot
    src: 'http://cultofthepartyparrot.com/parrots/margaritaparrot.gif'
  - name: oriolesparrot
    src: 'http://cultofthepartyparrot.com/parrots/oriolesparrot.gif'
  - name: dreidelparrot
    src: 'http://cultofthepartyparrot.com/parrots/dreidelparrot.gif'
  - name: harrypotterparrot
    src: 'http://cultofthepartyparrot.com/parrots/harrypotterparrot.gif'
  - name: fieriparrot
    src: 'http://cultofthepartyparrot.com/parrots/fieriparrot.gif'
  - name: upvotepartyparrot
    src: 'http://cultofthepartyparrot.com/parrots/upvotepartyparrot.gif'
  - name: twinsparrot
    src: 'http://cultofthepartyparrot.com/parrots/twinsparrot.gif'
  - name: tripletsparrot
    src: 'http://cultofthepartyparrot.com/parrots/tripletsparrot.gif'
  - name: stableparrot
    src: 'http://cultofthepartyparrot.com/parrots/stableparrot.gif'
  - name: shipitparrot
    src: 'http://cultofthepartyparrot.com/parrots/shipitparrot.gif'
  - name: skiparrot
    src: 'http://cultofthepartyparrot.com/parrots/skiparrot.gif'
  - name: halalparrot
    src: 'http://cultofthepartyparrot.com/parrots/halalparrot.gif'
```
